DELETE FROM state;
ALTER TABLE state AUTO_INCREMENT = 1;

INSERT INTO `person_ad`.`state` (`name`, `id_country`) VALUES ('San José', '1');
INSERT INTO `person_ad`.`state` (`name`, `id_country`) VALUES ('Alajuela', '1');
INSERT INTO `person_ad`.`state` (`name`, `id_country`) VALUES ('Cartago', '1');
INSERT INTO `person_ad`.`state` (`name`, `id_country`) VALUES ('Heredia', '1');
INSERT INTO `person_ad`.`state` (`name`, `id_country`) VALUES ('Guanacaste', '1');
INSERT INTO `person_ad`.`state` (`name`, `id_country`) VALUES ('Puntarenas', '1');
INSERT INTO `person_ad`.`state` (`name`, `id_country`) VALUES ('Limón', '1');
INSERT INTO `person_ad`.`state` (`name`, `id_country`) VALUES ('Alabama', '2');
INSERT INTO `person_ad`.`state` (`name`, `id_country`) VALUES ('California', '2');
INSERT INTO `person_ad`.`state` (`name`, `id_country`) VALUES ('Colorado', '2');
INSERT INTO `person_ad`.`state` (`name`, `id_country`) VALUES ('Florida', '2');
INSERT INTO `person_ad`.`state` (`name`, `id_country`) VALUES ('Nevada', '2');
INSERT INTO `person_ad`.`state` (`name`, `id_country`) VALUES ('New York', '2');
INSERT INTO `person_ad`.`state` (`name`, `id_country`) VALUES ('Washington', '2');
INSERT INTO `person_ad`.`state` (`name`, `id_country`) VALUES ('Baja California', '3');
INSERT INTO `person_ad`.`state` (`name`, `id_country`) VALUES ('Chiapas', '3');
INSERT INTO `person_ad`.`state` (`name`, `id_country`) VALUES ('Ciudad de México', '3');
INSERT INTO `person_ad`.`state` (`name`, `id_country`) VALUES ('Nuevo León', '3');
INSERT INTO `person_ad`.`state` (`name`, `id_country`) VALUES ('Oaxaca', '3');
INSERT INTO `person_ad`.`state` (`name`, `id_country`) VALUES ('Sinaloa', '3');
INSERT INTO `person_ad`.`state` (`name`, `id_country`) VALUES ('Yucatán', '3');
INSERT INTO `person_ad`.`state` (`name`, `id_country`) VALUES ('Bogotá', '4');
INSERT INTO `person_ad`.`state` (`name`, `id_country`) VALUES ('Bolívar', '4');
INSERT INTO `person_ad`.`state` (`name`, `id_country`) VALUES ('Magdalena', '4');