DELETE FROM city;
ALTER TABLE city AUTO_INCREMENT = 1;

INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('San José', '1');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Escazú', '1');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Desamparados', '1');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Tibás', '1');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Moravia', '1');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Curridabat', '1');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Alajuela', '2');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Grecia', '2');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Atenas', '2');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Naranjo', '2');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Orotina', '2');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Cartago', '3');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Paraíso', '3');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Turrialba', '3');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('El Guarco', '3');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Heredia', '4');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Barva', '4');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Santo Domingo', '4');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('San Pablo', '4');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Liberia', '5');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Nicoya', '5');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Tilarán', '5');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Hojancha', '5');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Puntarenas', '6');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Esparza', '6');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Golfito', '6');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Parrita', '6');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Limón', '7');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Pococí', '7');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Talamanca', '7');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Baldwin', '8');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Clay', '8');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Lauderdale', '8');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Los Ángeles', '9');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Boulder', '10');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Park', '10');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('DeSoto', '11');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Miami', '11');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Taylor', '11');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Churchill', '12');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Clark', '12');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Niagara', '13');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('New York', '13');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Adams', '14');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('King', '14');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Mexicali', '15');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Tijuana', '15');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Tapachula', '16');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Ciudad de México', '17');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Milpa Alta', '17');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Allende', '18');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Oaxaca de Juárez', '19');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Ahome', '20');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Baca', '21');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Santa Fe', '22');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Montecristo', '23');
INSERT INTO `person_ad`.`city` (`name`, `id_state`) VALUES ('Pivijay', '24');