DELETE FROM district;
ALTER TABLE district AUTO_INCREMENT = 1;

INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Carmen', '1');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Merced', '1');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Hospital', '1');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Catedral', '1');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Zapote', '1');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Pavas', '1');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('San Miguel', '2');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('San Antonio', '2');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Desamparados', '3');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Frailes', '3');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Rosario', '3');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Damas', '3');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('San Juan', '4');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Cinco Esquinas', '4');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Colima', '4');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('San Vicente', '5');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('San Jerónimo', '5');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('La Trinidad', '5');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Curridabat', '6');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Granadilla', '6');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Sánchez', '6');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Tirrases', '6');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Alajuela', '7');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Carrizal', '7');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Sabanilla', '7');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Grecia', '8');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('San Isidro', '8');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Atenas', '9');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Jesús', '9');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Concepción', '9');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Naranjo', '10');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Palmitos', '10');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Orotina', '11');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('La Ceiba', '11');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Oriental', '12');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('San Nicolás', '12');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Agua Caliente', '12');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Paraíso', '13');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Orosí', '13');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Cachí', '13');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Turrialba', '14');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Chirripó', '14');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('El Tejar', '15');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Tobosi', '15');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Heredia', '16');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Mercedes', '16');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Ulloa', '16');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Barva', '17');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Santa Lucía', '17');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('San José de la Montaña', '17');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Santo Domingo', '18');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('San Pablo', '19');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Liberia', '20');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Mayorga', '20');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Nicoya', '21');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Sámara', '21');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Nosara', '21');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Tilarán', '22');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Santa Rosa', '22');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Hojancha', '23');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Puntarenas', '24');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Paquera', '24');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Manzanillo', '24');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Monteverde', '24');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Espíritu Grande', '25');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('San Rafael', '25');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Golfito', '26');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Pavón', '26');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Parrita', '27');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Limón', '28');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Río Blanco', '28');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Guápiles', '29');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Cariari', '29');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Sixaola', '30');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Cahuita', '30');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Baldwin', '31');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Clay', '32');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Lauderdale', '33');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Los Ángeles', '34');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Boulder', '35');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Park', '36');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('DeSoto', '37');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Miami', '38');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Taylor', '39');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Churchill', '40');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Clark', '41');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Niagara', '42');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('New York', '43');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Adams', '44');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Seattle', '45');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Mexicali', '46');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Tijuana', '47');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Tapachula', '48');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Ciudad de México', '49');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Milpa Alta', '50');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Allende', '51');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Oaxaca de Juárez', '52');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Ahome', '53');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Baca', '54');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Santa Fe', '55');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Monte Cristo', '56');
INSERT INTO `person_ad`.`district` (`name`, `id_city`) VALUES ('Pivijay', '57');