/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import BL.person;
import BL.user;
import Connection.ConnectDB;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author sebas
 */
public class AddProduct extends javax.swing.JFrame {

    /**
     * Creates new form AddProduct
     */
    public AddProduct() {
        initComponents();
        fillCombo();
    }
    
        void fillCombo()
    {
        ConnectDB c = new ConnectDB();
        
        BoxCategory.removeAllItems();
        BoxCategory.addItem("Default");
        
        ResultSet category = c.query("`getAll_category`",true);
        
        BoxShipping.removeAllItems();
        BoxShipping.addItem("Default");
        
        ResultSet deliveryType = c.query("`getAll_delivery_type`",true);
        
        
        try {
            while(category.next())
            {
                BoxCategory.addItem(String.valueOf(category.getString("name")));
            }
            while(deliveryType.next())
            {
                BoxShipping.addItem(String.valueOf(deliveryType.getString("description")));
            }
        } catch (Exception ex) {
            System.out.println("Error: " + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonBack = new javax.swing.JButton();
        ButtonConfirm = new javax.swing.JButton();
        ButtonAddPic = new javax.swing.JButton();
        ButtonDeletePic = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FieldName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FieldDescription = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        BoxCategory = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        FieldPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        BoxShipping = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PanelPictures = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        FieldDescription1 = new javax.swing.JTextArea();
        Decoration1 = new javax.swing.JPanel();
        Decoration3 = new javax.swing.JPanel();
        Decoration2 = new javax.swing.JPanel();
        Decoration4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonBack.setBackground(new java.awt.Color(255, 255, 255));
        ButtonBack.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        ButtonBack.setForeground(new java.awt.Color(76, 40, 130));
        ButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back-arrow.png"))); // NOI18N
        ButtonBack.setBorder(null);
        ButtonBack.setContentAreaFilled(false);
        jPanel1.add(ButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 50, 50));

        ButtonConfirm.setBackground(new java.awt.Color(255, 255, 255));
        ButtonConfirm.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        ButtonConfirm.setForeground(new java.awt.Color(76, 40, 130));
        ButtonConfirm.setText("Confirm");
        ButtonConfirm.setBorder(null);
        ButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfirmActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, 110, 30));

        ButtonAddPic.setBackground(new java.awt.Color(255, 255, 255));
        ButtonAddPic.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        ButtonAddPic.setForeground(new java.awt.Color(76, 40, 130));
        ButtonAddPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add(1).png"))); // NOI18N
        ButtonAddPic.setBorder(null);
        ButtonAddPic.setContentAreaFilled(false);
        jPanel1.add(ButtonAddPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 50, 50));

        ButtonDeletePic.setBackground(new java.awt.Color(255, 255, 255));
        ButtonDeletePic.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        ButtonDeletePic.setForeground(new java.awt.Color(76, 40, 130));
        ButtonDeletePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close-button.png"))); // NOI18N
        ButtonDeletePic.setBorder(null);
        ButtonDeletePic.setContentAreaFilled(false);
        jPanel1.add(ButtonDeletePic, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 50, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(76, 40, 130));
        jLabel1.setText("Add product");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(76, 40, 130));
        jLabel3.setText("Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        FieldName.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        FieldName.setForeground(new java.awt.Color(76, 40, 130));
        jPanel1.add(FieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 190, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(76, 40, 130));
        jLabel5.setText("Description:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        FieldDescription.setColumns(20);
        FieldDescription.setRows(5);
        jScrollPane1.setViewportView(FieldDescription);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 240, 70));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(76, 40, 130));
        jLabel4.setText("Category:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        BoxCategory.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        BoxCategory.setForeground(new java.awt.Color(76, 40, 130));
        jPanel1.add(BoxCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 160, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(76, 40, 130));
        jLabel6.setText("Price:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        FieldPrice.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        FieldPrice.setForeground(new java.awt.Color(76, 40, 130));
        jPanel1.add(FieldPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 190, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(76, 40, 130));
        jLabel7.setText("Shipping Method:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        BoxShipping.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        BoxShipping.setForeground(new java.awt.Color(76, 40, 130));
        jPanel1.add(BoxShipping, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 160, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(76, 40, 130));
        jLabel8.setText("Pictures:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        PanelPictures.setBackground(new java.awt.Color(255, 255, 255));
        PanelPictures.setLayout(new java.awt.GridLayout(0, 3));
        jScrollPane2.setViewportView(PanelPictures);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 250, 100));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(76, 40, 130));
        jLabel9.setText("Seller Rating:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, -1, -1));

        FieldDescription1.setColumns(20);
        FieldDescription1.setRows(5);
        jScrollPane3.setViewportView(FieldDescription1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 240, 40));

        Decoration1.setBackground(new java.awt.Color(239, 184, 16));

        Decoration3.setBackground(new java.awt.Color(76, 40, 130));

        javax.swing.GroupLayout Decoration3Layout = new javax.swing.GroupLayout(Decoration3);
        Decoration3.setLayout(Decoration3Layout);
        Decoration3Layout.setHorizontalGroup(
            Decoration3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Decoration3Layout.setVerticalGroup(
            Decoration3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Decoration1Layout = new javax.swing.GroupLayout(Decoration1);
        Decoration1.setLayout(Decoration1Layout);
        Decoration1Layout.setHorizontalGroup(
            Decoration1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Decoration1Layout.createSequentialGroup()
                .addComponent(Decoration3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        Decoration1Layout.setVerticalGroup(
            Decoration1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Decoration1Layout.createSequentialGroup()
                .addComponent(Decoration3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jPanel1.add(Decoration1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, -1));

        Decoration2.setBackground(new java.awt.Color(239, 184, 16));

        Decoration4.setBackground(new java.awt.Color(76, 40, 130));

        javax.swing.GroupLayout Decoration4Layout = new javax.swing.GroupLayout(Decoration4);
        Decoration4.setLayout(Decoration4Layout);
        Decoration4Layout.setHorizontalGroup(
            Decoration4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Decoration4Layout.setVerticalGroup(
            Decoration4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Decoration2Layout = new javax.swing.GroupLayout(Decoration2);
        Decoration2.setLayout(Decoration2Layout);
        Decoration2Layout.setHorizontalGroup(
            Decoration2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Decoration2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Decoration4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Decoration2Layout.setVerticalGroup(
            Decoration2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Decoration2Layout.createSequentialGroup()
                .addComponent(Decoration4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jPanel1.add(Decoration2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfirmActionPerformed
        ConnectDB c = new ConnectDB();
        var name = FieldName.getText();
        var description = FieldDescription.getText();
        var price = FieldPrice.getText();
        var picture_path = "";
        String category_element = (String) BoxCategory.getSelectedItem();
        String delivery_type_element = (String) BoxShipping.getSelectedItem();
        if(category_element == "Default")  
            JOptionPane.showMessageDialog(this, "Select the category box.");
        else if(delivery_type_element == "Default")
            JOptionPane.showMessageDialog(this, "Select the shipping box.");
        else if(name == "")
        {
            JOptionPane.showMessageDialog(this, "Fill the name field.");
        }
        else if(description == "")
        {
            JOptionPane.showMessageDialog(this, "Fill the description field.");
        }
        else if(price == "")
        {
            JOptionPane.showMessageDialog(this, "Fill the price field.");
        }
        else
        {
            var id_category = c.getIntWithString(category_element, "getId_category", true);
            var id_delivery_type = c.getIntWithString(delivery_type_element, "getId_delivery_type", true);
            //product p = new product(price, name, description, quantityInStock, isVisible, id_category, usernameSeller, id_delivery_type);
            //c.insertProduct(p);
            JOptionPane.showMessageDialog(this, "The product was inserted successfully in the system.");
        }
    }//GEN-LAST:event_ButtonConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxCategory;
    private javax.swing.JComboBox<String> BoxShipping;
    private javax.swing.JButton ButtonAddPic;
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton ButtonConfirm;
    private javax.swing.JButton ButtonDeletePic;
    private javax.swing.JPanel Decoration1;
    private javax.swing.JPanel Decoration2;
    private javax.swing.JPanel Decoration3;
    private javax.swing.JPanel Decoration4;
    private javax.swing.JTextArea FieldDescription;
    private javax.swing.JTextArea FieldDescription1;
    private javax.swing.JTextField FieldName;
    private javax.swing.JTextField FieldPrice;
    private javax.swing.JPanel PanelPictures;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
