/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

/**
 *
 * @author diana
 */
public class PanelPrincipalPage extends javax.swing.JPanel {

    /**
     * Creates new form PanelPrincipalPage
     */
    public PanelPrincipalPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonProfile = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonProfile.setBackground(new java.awt.Color(255, 255, 255));
        ButtonProfile.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        ButtonProfile.setForeground(new java.awt.Color(76, 40, 130));
        ButtonProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user(1).png"))); // NOI18N
        ButtonProfile.setBorder(null);
        add(ButtonProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 70, 70));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonProfile;
    // End of variables declaration//GEN-END:variables
}
