/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

/**
 *
 * @author diana
 */
public class PanelProfile extends javax.swing.JPanel {

    /**
     * Creates new form PanelMyProfile
     */
    public PanelProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SpaceName = new javax.swing.JLabel();
        SpaceResidence = new javax.swing.JLabel();
        SpaceRatingSeller = new javax.swing.JLabel();
        SpaceRatingBuyer = new javax.swing.JLabel();
        ButtonContact = new javax.swing.JButton();
        ButtonBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PanelProducts = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PanelComments = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        ButtonPicture = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/location.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 132, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(76, 40, 130));
        jLabel2.setText("Products");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 200, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(76, 40, 130));
        jLabel3.setText("Comments");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 280, 200, -1));

        SpaceName.setBackground(new java.awt.Color(255, 255, 255));
        SpaceName.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        SpaceName.setForeground(new java.awt.Color(76, 40, 130));
        SpaceName.setText("Name of the user");
        add(SpaceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 200, -1));

        SpaceResidence.setBackground(new java.awt.Color(255, 255, 255));
        SpaceResidence.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        SpaceResidence.setForeground(new java.awt.Color(76, 40, 130));
        SpaceResidence.setText("City, Country Residence");
        add(SpaceResidence, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 200, -1));

        SpaceRatingSeller.setBackground(new java.awt.Color(255, 255, 255));
        SpaceRatingSeller.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        SpaceRatingSeller.setForeground(new java.awt.Color(76, 40, 130));
        SpaceRatingSeller.setText("Rating Seller");
        add(SpaceRatingSeller, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 200, -1));

        SpaceRatingBuyer.setBackground(new java.awt.Color(255, 255, 255));
        SpaceRatingBuyer.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        SpaceRatingBuyer.setForeground(new java.awt.Color(76, 40, 130));
        SpaceRatingBuyer.setText("Rating Buyer");
        add(SpaceRatingBuyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 200, -1));

        ButtonContact.setBackground(new java.awt.Color(255, 255, 255));
        ButtonContact.setFont(new java.awt.Font("Candara", 1, 20)); // NOI18N
        ButtonContact.setForeground(new java.awt.Color(76, 40, 130));
        ButtonContact.setText("Contact");
        ButtonContact.setBorder(null);
        ButtonContact.setContentAreaFilled(false);
        add(ButtonContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, 120, 40));

        ButtonBack.setBackground(new java.awt.Color(255, 255, 255));
        ButtonBack.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        ButtonBack.setForeground(new java.awt.Color(76, 40, 130));
        ButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back-arrow.png"))); // NOI18N
        ButtonBack.setBorder(null);
        ButtonBack.setContentAreaFilled(false);
        add(ButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        PanelProducts.setBackground(new java.awt.Color(255, 255, 255));
        PanelProducts.setLayout(new java.awt.GridLayout(0, 3));
        jScrollPane1.setViewportView(PanelProducts);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 320, 220));

        PanelComments.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(PanelComments);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 370, 220));

        jPanel1.setBackground(new java.awt.Color(239, 184, 16));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 50, 580));

        ButtonPicture.setBackground(new java.awt.Color(255, 255, 255));
        ButtonPicture.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        ButtonPicture.setForeground(new java.awt.Color(76, 40, 130));
        ButtonPicture.setText("Picture");
        ButtonPicture.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(76, 40, 130), 2, true));
        ButtonPicture.setContentAreaFilled(false);
        add(ButtonPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 120, 150));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton ButtonContact;
    private javax.swing.JButton ButtonPicture;
    private javax.swing.JList<String> PanelComments;
    private javax.swing.JPanel PanelProducts;
    private javax.swing.JLabel SpaceName;
    private javax.swing.JLabel SpaceRatingBuyer;
    private javax.swing.JLabel SpaceRatingSeller;
    private javax.swing.JLabel SpaceResidence;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
