/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

/**
 *
 * @author diana
 */
public class PanelProductsSettings extends javax.swing.JPanel {

    /**
     * Creates new form PanelAddProduct
     */
    public PanelProductsSettings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ButtonAddProduct = new javax.swing.JButton();
        ButtonEditProduct = new javax.swing.JButton();
        ButtonDeleteProduct = new javax.swing.JButton();
        ButtonCancel = new javax.swing.JButton();
        ButtonConfirm = new javax.swing.JButton();
        ButtonBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PanelProducts = new javax.swing.JPanel();
        Decoration = new javax.swing.JPanel();
        Decoration1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(76, 40, 130));
        jLabel1.setText("Products Settings");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 40, -1, -1));

        ButtonAddProduct.setBackground(new java.awt.Color(255, 255, 255));
        ButtonAddProduct.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        ButtonAddProduct.setForeground(new java.awt.Color(76, 40, 130));
        ButtonAddProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/paint-palette.png"))); // NOI18N
        ButtonAddProduct.setBorder(null);
        ButtonAddProduct.setContentAreaFilled(false);
        add(ButtonAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 250, 80, 80));

        ButtonEditProduct.setBackground(new java.awt.Color(255, 255, 255));
        ButtonEditProduct.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        ButtonEditProduct.setForeground(new java.awt.Color(76, 40, 130));
        ButtonEditProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add.png"))); // NOI18N
        ButtonEditProduct.setBorder(null);
        ButtonEditProduct.setContentAreaFilled(false);
        add(ButtonEditProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, 80, 80));

        ButtonDeleteProduct.setBackground(new java.awt.Color(255, 255, 255));
        ButtonDeleteProduct.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        ButtonDeleteProduct.setForeground(new java.awt.Color(76, 40, 130));
        ButtonDeleteProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cross-square-black-button.png"))); // NOI18N
        ButtonDeleteProduct.setBorder(null);
        ButtonDeleteProduct.setContentAreaFilled(false);
        add(ButtonDeleteProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 390, 80, 80));

        ButtonCancel.setBackground(new java.awt.Color(255, 255, 255));
        ButtonCancel.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        ButtonCancel.setForeground(new java.awt.Color(76, 40, 130));
        ButtonCancel.setText("Cancel");
        ButtonCancel.setBorder(null);
        add(ButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, 110, 30));

        ButtonConfirm.setBackground(new java.awt.Color(255, 255, 255));
        ButtonConfirm.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        ButtonConfirm.setForeground(new java.awt.Color(76, 40, 130));
        ButtonConfirm.setText("Confirm");
        ButtonConfirm.setBorder(null);
        add(ButtonConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 110, 30));

        ButtonBack.setBackground(new java.awt.Color(255, 255, 255));
        ButtonBack.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        ButtonBack.setForeground(new java.awt.Color(76, 40, 130));
        ButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back-arrow.png"))); // NOI18N
        ButtonBack.setBorder(null);
        ButtonBack.setContentAreaFilled(false);
        add(ButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        PanelProducts.setBackground(new java.awt.Color(255, 255, 255));
        PanelProducts.setLayout(new java.awt.GridLayout(0, 3));
        jScrollPane1.setViewportView(PanelProducts);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 730, 370));

        Decoration.setBackground(new java.awt.Color(239, 184, 16));

        javax.swing.GroupLayout DecorationLayout = new javax.swing.GroupLayout(Decoration);
        Decoration.setLayout(DecorationLayout);
        DecorationLayout.setHorizontalGroup(
            DecorationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DecorationLayout.setVerticalGroup(
            DecorationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(Decoration, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 90, 490));

        Decoration1.setBackground(new java.awt.Color(76, 40, 130));

        javax.swing.GroupLayout Decoration1Layout = new javax.swing.GroupLayout(Decoration1);
        Decoration1.setLayout(Decoration1Layout);
        Decoration1Layout.setHorizontalGroup(
            Decoration1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Decoration1Layout.setVerticalGroup(
            Decoration1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(Decoration1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 70, 90, 490));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAddProduct;
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton ButtonCancel;
    private javax.swing.JButton ButtonConfirm;
    private javax.swing.JButton ButtonDeleteProduct;
    private javax.swing.JButton ButtonEditProduct;
    private javax.swing.JPanel Decoration;
    private javax.swing.JPanel Decoration1;
    private javax.swing.JPanel PanelProducts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
