/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import BL.product;
import BL.shopping_cart;
import Connection.ConnectDB;
import Connection.currentUser;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sebas
 */
public class ProductView extends javax.swing.JFrame {

    product p;
    public ProductView() {
        initComponents();
    }
    
    public ProductView(int pId) {
        initComponents();
        currentUser cu = currentUser.getInstance(); 
        
        ConnectDB c = new ConnectDB();
        try {
            ResultSet prod = c.queryWithInt(pId, "get_product_with_id",true);
            product p = new product(prod.getFloat("price"),
                                    prod.getString("name"),
                                    prod.getString("description"),
                                    prod.getInt("quant_in_stock"),
                                    prod.getBoolean("is_visible"),
                                    prod.getFloat("average_score"),
                                    prod.getInt("id_category"),
                                    prod.getString("username_seller"),
                                    prod.getInt("id_delivery_type"));
            p.setId(pId);      
            this.p = p;
        } catch (Exception ex) {
          JOptionPane.showMessageDialog(this, "Error. Try later.");
        }
        fillIn();
        cu.insertInHistory(p);
    }
    
    public void fillIn()
    {
        currentUser cu = currentUser.getInstance();    
        ConnectDB c = new ConnectDB();
        FieldName.setEnabled(false);
        FieldDescription.setEnabled(false);
        FieldCategory.setEnabled(false);
        FieldPrice.setEnabled(false);
        FieldSeller.setEnabled(false);
        FieldReviewSeller.setEnabled(false);
        
        FieldName.setText(p.getName());
        FieldDescription.setText(p.getDescription());
        FieldCategory.setText(c.getStringWithInt(p.getId_category(), "getName_category", true));
        FieldPrice.setText(Float.toString(p.getPrice()));
        FieldSeller.setText(p.getUsername_seller());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ButtonPicture = new javax.swing.JButton();
        ButtonLeft = new javax.swing.JButton();
        ButtonRight = new javax.swing.JButton();
        ButtonConfirm = new javax.swing.JButton();
        ButtonBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        FieldName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FieldDescription = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        FieldCategory = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        FieldPrice = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        FieldSeller = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        FieldReviewSeller = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableBuyerReview = new javax.swing.JTable();
        Decoration5 = new javax.swing.JPanel();
        Decoration4 = new javax.swing.JPanel();
        Decoration6 = new javax.swing.JPanel();
        Decoration8 = new javax.swing.JPanel();
        FieldName1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        FieldQuantity = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        ButtonConfirm1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(76, 40, 130));
        jLabel1.setText("Product View");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        ButtonPicture.setBackground(new java.awt.Color(255, 255, 255));
        ButtonPicture.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        ButtonPicture.setForeground(new java.awt.Color(76, 40, 130));
        ButtonPicture.setText("Picture");
        ButtonPicture.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(76, 40, 130), 2, true));
        ButtonPicture.setContentAreaFilled(false);
        jPanel1.add(ButtonPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 120, 150));

        ButtonLeft.setBackground(new java.awt.Color(255, 255, 255));
        ButtonLeft.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        ButtonLeft.setForeground(new java.awt.Color(76, 40, 130));
        ButtonLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/video-player(1).png"))); // NOI18N
        ButtonLeft.setBorder(null);
        ButtonLeft.setContentAreaFilled(false);
        jPanel1.add(ButtonLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 50, 50));

        ButtonRight.setBackground(new java.awt.Color(255, 255, 255));
        ButtonRight.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        ButtonRight.setForeground(new java.awt.Color(76, 40, 130));
        ButtonRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/video-player.png"))); // NOI18N
        ButtonRight.setBorder(null);
        ButtonRight.setContentAreaFilled(false);
        jPanel1.add(ButtonRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 50, 50));

        ButtonConfirm.setBackground(new java.awt.Color(255, 255, 255));
        ButtonConfirm.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        ButtonConfirm.setForeground(new java.awt.Color(76, 40, 130));
        ButtonConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/shopping-basket.png"))); // NOI18N
        ButtonConfirm.setText("  Add to the basket");
        ButtonConfirm.setBorder(null);
        ButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfirmActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 240, 50));

        ButtonBack.setBackground(new java.awt.Color(255, 255, 255));
        ButtonBack.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        ButtonBack.setForeground(new java.awt.Color(76, 40, 130));
        ButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back-arrow.png"))); // NOI18N
        ButtonBack.setBorder(null);
        ButtonBack.setContentAreaFilled(false);
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(76, 40, 130));
        jLabel3.setText("Seller:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, -1, -1));

        FieldName.setBackground(new java.awt.Color(255, 255, 255));
        FieldName.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        FieldName.setForeground(new java.awt.Color(76, 40, 130));
        jPanel1.add(FieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 190, 20));

        jSeparator1.setForeground(new java.awt.Color(76, 40, 130));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 190, 20));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(76, 40, 130));
        jLabel5.setText("Description:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        FieldDescription.setColumns(20);
        FieldDescription.setRows(5);
        jScrollPane1.setViewportView(FieldDescription);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 240, 70));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(76, 40, 130));
        jLabel4.setText("Category:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        FieldCategory.setBackground(new java.awt.Color(255, 255, 255));
        FieldCategory.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        FieldCategory.setForeground(new java.awt.Color(76, 40, 130));
        jPanel1.add(FieldCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 190, 20));

        jSeparator2.setForeground(new java.awt.Color(76, 40, 130));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 190, 20));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(76, 40, 130));
        jLabel6.setText("Price:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        FieldPrice.setBackground(new java.awt.Color(255, 255, 255));
        FieldPrice.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        FieldPrice.setForeground(new java.awt.Color(76, 40, 130));
        jPanel1.add(FieldPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 190, 20));

        jSeparator3.setForeground(new java.awt.Color(76, 40, 130));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 190, 20));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(76, 40, 130));
        jLabel8.setText("Pictures:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(76, 40, 130));
        jLabel7.setText("Name:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        FieldSeller.setBackground(new java.awt.Color(255, 255, 255));
        FieldSeller.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        FieldSeller.setForeground(new java.awt.Color(76, 40, 130));
        jPanel1.add(FieldSeller, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 190, 20));

        jSeparator4.setForeground(new java.awt.Color(76, 40, 130));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 190, 20));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(76, 40, 130));
        jLabel9.setText("Seller review:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, -1, -1));

        FieldReviewSeller.setColumns(20);
        FieldReviewSeller.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        FieldReviewSeller.setForeground(new java.awt.Color(76, 40, 130));
        FieldReviewSeller.setRows(5);
        jScrollPane3.setViewportView(FieldReviewSeller);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 220, 70));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(76, 40, 130));
        jLabel10.setText("Score:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(76, 40, 130));
        jLabel11.setText("Estrellitas");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(76, 40, 130));
        jLabel12.setText("Buyers review:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, -1, -1));

        jScrollPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 40, 130)));
        jScrollPane4.setForeground(new java.awt.Color(76, 40, 130));

        TableBuyerReview.setAutoCreateColumnsFromModel(false);
        TableBuyerReview.setAutoCreateRowSorter(true);
        TableBuyerReview.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        TableBuyerReview.setForeground(new java.awt.Color(76, 40, 130));
        TableBuyerReview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "User", "Comment"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(TableBuyerReview);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 400, 110));

        Decoration5.setBackground(new java.awt.Color(239, 184, 16));
        Decoration5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(Decoration5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 60, 100));

        Decoration4.setBackground(new java.awt.Color(239, 184, 16));
        Decoration4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(Decoration4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, 60, 100));

        Decoration6.setBackground(new java.awt.Color(76, 40, 130));

        javax.swing.GroupLayout Decoration6Layout = new javax.swing.GroupLayout(Decoration6);
        Decoration6.setLayout(Decoration6Layout);
        Decoration6Layout.setHorizontalGroup(
            Decoration6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        Decoration6Layout.setVerticalGroup(
            Decoration6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(Decoration6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 60, 100));

        Decoration8.setBackground(new java.awt.Color(76, 40, 130));

        javax.swing.GroupLayout Decoration8Layout = new javax.swing.GroupLayout(Decoration8);
        Decoration8.setLayout(Decoration8Layout);
        Decoration8Layout.setHorizontalGroup(
            Decoration8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        Decoration8Layout.setVerticalGroup(
            Decoration8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(Decoration8, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 60, 100));

        FieldName1.setBackground(new java.awt.Color(255, 255, 255));
        FieldName1.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        FieldName1.setForeground(new java.awt.Color(76, 40, 130));
        jPanel1.add(FieldName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 190, 20));

        jSeparator5.setForeground(new java.awt.Color(76, 40, 130));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 190, 20));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(76, 40, 130));
        jLabel13.setText("Quantity:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, -1, -1));

        FieldQuantity.setBackground(new java.awt.Color(255, 255, 255));
        FieldQuantity.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        FieldQuantity.setForeground(new java.awt.Color(76, 40, 130));
        jPanel1.add(FieldQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 160, 20));

        jSeparator6.setForeground(new java.awt.Color(76, 40, 130));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, 160, 20));

        ButtonConfirm1.setBackground(new java.awt.Color(255, 255, 255));
        ButtonConfirm1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        ButtonConfirm1.setForeground(new java.awt.Color(76, 40, 130));
        ButtonConfirm1.setText("See Profile");
        ButtonConfirm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfirm1ActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonConfirm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 110, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfirmActionPerformed
        String quantity_element = FieldQuantity.getText();
        if(quantity_element.isEmpty())
            JOptionPane.showMessageDialog(this, "Fill the quantity field.");
        else
        {
            try{
                currentUser cu = currentUser.getInstance(); 
                ConnectDB c = new ConnectDB();
                shopping_cart sc = new shopping_cart(cu.getUsername(),p.getId() , Integer.parseInt(quantity_element));
                c.insertShoppingCart(sc);
                JOptionPane.showMessageDialog(this, "The product was added to the basket succesfully.");
            }catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this, "The product was not added to the basket.");
            }
        }
    }//GEN-LAST:event_ButtonConfirmActionPerformed

    private void ButtonConfirm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfirm1ActionPerformed
        Profile w = new Profile(FieldSeller.getText());
        w.show();
        this.dispose();
    }//GEN-LAST:event_ButtonConfirm1ActionPerformed

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        //Profile w = new Profile(FieldSeller.getText());
        //w.show();
        //this.dispose();
    }//GEN-LAST:event_ButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton ButtonConfirm;
    private javax.swing.JButton ButtonConfirm1;
    private javax.swing.JButton ButtonLeft;
    private javax.swing.JButton ButtonPicture;
    private javax.swing.JButton ButtonRight;
    private javax.swing.JPanel Decoration4;
    private javax.swing.JPanel Decoration5;
    private javax.swing.JPanel Decoration6;
    private javax.swing.JPanel Decoration8;
    private javax.swing.JLabel FieldCategory;
    private javax.swing.JTextArea FieldDescription;
    private javax.swing.JLabel FieldName;
    private javax.swing.JLabel FieldName1;
    private javax.swing.JLabel FieldPrice;
    private javax.swing.JLabel FieldQuantity;
    private javax.swing.JTextArea FieldReviewSeller;
    private javax.swing.JLabel FieldSeller;
    private javax.swing.JTable TableBuyerReview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
