
package Frame;

import Connection.ConnectDB;
import Connection.currentUser;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Profile extends javax.swing.JFrame {

    private String username;
    
    public Profile(String username) {
        initComponents();
        setLocationRelativeTo(null);
        this.username = username;
        fillIn();
        
    }

    private Profile() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    private void fillIn() {
        ConnectDB c = new ConnectDB();
        currentUser cu = currentUser.getInstance();
        
        ContactComboBox.removeAllItems();
        ContactComboBox.addItem("Default");
        
        
        ReviewsTextArea.setEditable(false);
        ReviewsTextArea.setLineWrap(true);
        ReviewsTextArea.setWrapStyleWord(true);   
        ReviewsTextArea.setText("");
        
        SpaceName.setText(username);
        
        ResultSet person = c.queryWithString(username, "get_person_with_username", false);
        ResultSet reviews = c.queryWithString(username, "get_reviews_of_user", true);
        ResultSet user = c.queryWithString(username, "get_user_with_username", true);
        ResultSet orders = c.queryWithStrings(cu.getUsername(), username, "get_orders_of_2_users", true);
        
        try { 
            person.next();
            SpaceResidence.setText(person.getString("district") + ", " + 
                    person.getString("city") + ", " +
                    person.getString("state") + ", " +
                    person.getString("country"));
            user.next();
            SpaceRatingSeller1.setText(user.getFloat("average_score_seller") + "/5");
            SpaceRatingSeller2.setText(user.getFloat("average_score_buyer") + "/5");
            String reviewsText = "";
            while (reviews.next()) {
                reviewsText = reviewsText + reviews.getString("username_writer") + 
                " (" + reviews.getFloat("score") + ", " + 
                reviews.getString("name") + "):" + reviews.getString("comment") + "\n";
            }
            while (orders.next()) {
                ContactComboBox.addItem(orders.getInt("id") + " " + orders.getString("name"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error. Try later.");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SpaceName = new javax.swing.JLabel();
        SpaceResidence = new javax.swing.JLabel();
        SpaceRatingSeller = new javax.swing.JLabel();
        SpaceRatingBuyer = new javax.swing.JLabel();
        ButtonContact = new javax.swing.JButton();
        ButtonBack = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ButtonPicture = new javax.swing.JButton();
        SpaceRatingSeller1 = new javax.swing.JLabel();
        SpaceRatingSeller2 = new javax.swing.JLabel();
        ContactComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReviewsTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/location.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 132, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(76, 40, 130));
        jLabel3.setText("Reviews");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 200, -1));

        SpaceName.setBackground(new java.awt.Color(255, 255, 255));
        SpaceName.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        SpaceName.setForeground(new java.awt.Color(76, 40, 130));
        SpaceName.setText("Name of the user");
        jPanel1.add(SpaceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 200, -1));

        SpaceResidence.setBackground(new java.awt.Color(255, 255, 255));
        SpaceResidence.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        SpaceResidence.setForeground(new java.awt.Color(76, 40, 130));
        SpaceResidence.setText("City, Country Residence");
        jPanel1.add(SpaceResidence, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 420, -1));

        SpaceRatingSeller.setBackground(new java.awt.Color(255, 255, 255));
        SpaceRatingSeller.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        SpaceRatingSeller.setForeground(new java.awt.Color(76, 40, 130));
        SpaceRatingSeller.setText("Rating as seller");
        jPanel1.add(SpaceRatingSeller, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 140, -1));

        SpaceRatingBuyer.setBackground(new java.awt.Color(255, 255, 255));
        SpaceRatingBuyer.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        SpaceRatingBuyer.setForeground(new java.awt.Color(76, 40, 130));
        SpaceRatingBuyer.setText("Rating as buyer");
        jPanel1.add(SpaceRatingBuyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 130, -1));

        ButtonContact.setBackground(new java.awt.Color(255, 255, 255));
        ButtonContact.setFont(new java.awt.Font("Candara", 1, 20)); // NOI18N
        ButtonContact.setForeground(new java.awt.Color(76, 40, 130));
        ButtonContact.setText("Contact");
        ButtonContact.setBorder(null);
        ButtonContact.setContentAreaFilled(false);
        ButtonContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonContactActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, 120, 40));

        ButtonBack.setBackground(new java.awt.Color(255, 255, 255));
        ButtonBack.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        ButtonBack.setForeground(new java.awt.Color(76, 40, 130));
        ButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back-arrow.png"))); // NOI18N
        ButtonBack.setBorder(null);
        ButtonBack.setContentAreaFilled(false);
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jPanel2.setBackground(new java.awt.Color(239, 184, 16));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 50, 580));

        ButtonPicture.setBackground(new java.awt.Color(255, 255, 255));
        ButtonPicture.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        ButtonPicture.setForeground(new java.awt.Color(76, 40, 130));
        ButtonPicture.setText("Picture");
        ButtonPicture.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(76, 40, 130), 2, true));
        ButtonPicture.setContentAreaFilled(false);
        jPanel1.add(ButtonPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 120, 150));

        SpaceRatingSeller1.setBackground(new java.awt.Color(255, 255, 255));
        SpaceRatingSeller1.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        SpaceRatingSeller1.setForeground(new java.awt.Color(76, 40, 130));
        SpaceRatingSeller1.setText("estrellitas");
        jPanel1.add(SpaceRatingSeller1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 120, -1));

        SpaceRatingSeller2.setBackground(new java.awt.Color(255, 255, 255));
        SpaceRatingSeller2.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        SpaceRatingSeller2.setForeground(new java.awt.Color(76, 40, 130));
        SpaceRatingSeller2.setText("estrellitas");
        jPanel1.add(SpaceRatingSeller2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 120, -1));

        ContactComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ContactComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default" }));
        ContactComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(ContactComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 200, 30));

        ReviewsTextArea.setColumns(20);
        ReviewsTextArea.setRows(5);
        jScrollPane1.setViewportView(ReviewsTextArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 620, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        PanelPrincipalPage w = new PanelPrincipalPage();
        w.show();
        this.dispose();
    }//GEN-LAST:event_ButtonBackActionPerformed

    private void ButtonContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonContactActionPerformed
        ConnectDB c = new ConnectDB();
        currentUser cu = currentUser.getInstance();
        String contact_order = (String) ContactComboBox.getSelectedItem();
        try {
            if("Default".equals(contact_order))
                JOptionPane.showMessageDialog(this, "Error. Please select an order from the contact box.");
            else
            {
                int id_order = Integer.valueOf(contact_order.substring(0, contact_order.indexOf(" ")));
                int id_chat = c.getIntWithId(id_order, "get_idChat_with_idOrder", true);
                Chat chat = new Chat(id_chat, username, cu.getUsername());
                chat.show();
                this.dispose();
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error. Try later.");
        }
    }//GEN-LAST:event_ButtonContactActionPerformed

    private void ContactComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton ButtonContact;
    private javax.swing.JButton ButtonPicture;
    private javax.swing.JComboBox<String> ContactComboBox;
    private javax.swing.JTextArea ReviewsTextArea;
    private javax.swing.JLabel SpaceName;
    private javax.swing.JLabel SpaceRatingBuyer;
    private javax.swing.JLabel SpaceRatingSeller;
    private javax.swing.JLabel SpaceRatingSeller1;
    private javax.swing.JLabel SpaceRatingSeller2;
    private javax.swing.JLabel SpaceResidence;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
