package Frame;
import Connection.ConnectDB;
import javax. swing.JFrame;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;


/**
 *
 * @author diana
 */
public class Statistics extends javax.swing.JFrame {

    /**
     * Creates new form Statistics
     */
    public Statistics() {
        initComponents();
        FillIn();
    }
    
    public void FillIn(){
        
        ConnectDB c = new ConnectDB();
        
        BoxGender.removeAllItems();
        BoxGender.addItem("Default");

        ResultSet gender = c.query("getAll_gender",false);
        
        try {
            while(gender.next())
            {
                BoxGender.addItem(String.valueOf(gender.getString("name")));
            }
        } catch (Exception ex) {
            System.out.println("Error: " + ex);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelProductsCategory = new javax.swing.JPanel();
        ButtonBack = new javax.swing.JButton();
        ButtonConfirm4 = new javax.swing.JButton();
        PanelTotalSellers = new javax.swing.JPanel();
        ButtonBack1 = new javax.swing.JButton();
        ButtonConfirm1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        BoxGender = new javax.swing.JComboBox<>();
        PanelTotalSales = new javax.swing.JPanel();
        ButtonBack2 = new javax.swing.JButton();
        ButtonConfirm2 = new javax.swing.JButton();
        PanelTotalAmountSales = new javax.swing.JPanel();
        ButtonBack3 = new javax.swing.JButton();
        ButtonConfirm5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(76, 40, 130));
        jTabbedPane1.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N

        PanelProductsCategory.setBackground(new java.awt.Color(255, 255, 255));
        PanelProductsCategory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonBack.setBackground(new java.awt.Color(255, 255, 255));
        ButtonBack.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        ButtonBack.setForeground(new java.awt.Color(76, 40, 130));
        ButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back-arrow.png"))); // NOI18N
        ButtonBack.setBorder(null);
        ButtonBack.setContentAreaFilled(false);
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });
        PanelProductsCategory.add(ButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        ButtonConfirm4.setBackground(new java.awt.Color(255, 255, 255));
        ButtonConfirm4.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        ButtonConfirm4.setForeground(new java.awt.Color(76, 40, 130));
        ButtonConfirm4.setText("Show");
        ButtonConfirm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfirm4ActionPerformed(evt);
            }
        });
        PanelProductsCategory.add(ButtonConfirm4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 110, 30));

        jTabbedPane1.addTab("Products by category", PanelProductsCategory);

        PanelTotalSellers.setBackground(new java.awt.Color(255, 255, 255));
        PanelTotalSellers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonBack1.setBackground(new java.awt.Color(255, 255, 255));
        ButtonBack1.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        ButtonBack1.setForeground(new java.awt.Color(76, 40, 130));
        ButtonBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back-arrow.png"))); // NOI18N
        ButtonBack1.setBorder(null);
        ButtonBack1.setContentAreaFilled(false);
        ButtonBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBack1ActionPerformed(evt);
            }
        });
        PanelTotalSellers.add(ButtonBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        ButtonConfirm1.setBackground(new java.awt.Color(255, 255, 255));
        ButtonConfirm1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        ButtonConfirm1.setForeground(new java.awt.Color(76, 40, 130));
        ButtonConfirm1.setText("Confirm");
        ButtonConfirm1.setBorder(null);
        ButtonConfirm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfirm1ActionPerformed(evt);
            }
        });
        PanelTotalSellers.add(ButtonConfirm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 110, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(76, 40, 130));
        jLabel4.setText("Gender:");
        PanelTotalSellers.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        BoxGender.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        BoxGender.setForeground(new java.awt.Color(76, 40, 130));
        PanelTotalSellers.add(BoxGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 170, 30));

        jTabbedPane1.addTab("Total sellers", PanelTotalSellers);

        PanelTotalSales.setBackground(new java.awt.Color(255, 255, 255));
        PanelTotalSales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonBack2.setBackground(new java.awt.Color(255, 255, 255));
        ButtonBack2.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        ButtonBack2.setForeground(new java.awt.Color(76, 40, 130));
        ButtonBack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back-arrow.png"))); // NOI18N
        ButtonBack2.setBorder(null);
        ButtonBack2.setContentAreaFilled(false);
        ButtonBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBack2ActionPerformed(evt);
            }
        });
        PanelTotalSales.add(ButtonBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        ButtonConfirm2.setBackground(new java.awt.Color(255, 255, 255));
        ButtonConfirm2.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        ButtonConfirm2.setForeground(new java.awt.Color(76, 40, 130));
        ButtonConfirm2.setText("Show");
        ButtonConfirm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfirm2ActionPerformed(evt);
            }
        });
        PanelTotalSales.add(ButtonConfirm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 110, 30));

        jTabbedPane1.addTab("Total sales", PanelTotalSales);

        PanelTotalAmountSales.setBackground(new java.awt.Color(255, 255, 255));
        PanelTotalAmountSales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonBack3.setBackground(new java.awt.Color(255, 255, 255));
        ButtonBack3.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        ButtonBack3.setForeground(new java.awt.Color(76, 40, 130));
        ButtonBack3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back-arrow.png"))); // NOI18N
        ButtonBack3.setBorder(null);
        ButtonBack3.setContentAreaFilled(false);
        ButtonBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBack3ActionPerformed(evt);
            }
        });
        PanelTotalAmountSales.add(ButtonBack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        ButtonConfirm5.setBackground(new java.awt.Color(255, 255, 255));
        ButtonConfirm5.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        ButtonConfirm5.setForeground(new java.awt.Color(76, 40, 130));
        ButtonConfirm5.setText("Show");
        ButtonConfirm5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfirm5ActionPerformed(evt);
            }
        });
        PanelTotalAmountSales.add(ButtonConfirm5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 110, 30));

        jTabbedPane1.addTab("Total amount of sales", PanelTotalAmountSales);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        PanelPrincipalPage w = new PanelPrincipalPage();
        w.show();
        this.dispose();
    }//GEN-LAST:event_ButtonBackActionPerformed

    private void ButtonBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBack1ActionPerformed
        PanelPrincipalPage w = new PanelPrincipalPage();
        w.show();
        this.dispose();
    }//GEN-LAST:event_ButtonBack1ActionPerformed

    private void ButtonConfirm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfirm1ActionPerformed
        ConnectDB c = new ConnectDB();
        String gender_element = (String) BoxGender.getSelectedItem();
        int id_gender;
        if(gender_element == "Default")
            id_gender = 0;
        else
            id_gender = c.getIntWithString(gender_element, "getId_gender", false);
        ResultSet q = c.queryWithInt(1,"gender_age_range_sellers",true);
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        try {
            while(q.next())
            {
                dataset.addValue(q.getInt("percentage"), Integer.toString(q.getInt("users")), q.getString("age_range"));
            }
        JFreeChart barChart = ChartFactory.createBarChart("Sales by Gender", "Age", "Quantity", dataset, PlotOrientation.VERTICAL,true, true, false);
        ChartPanel panel = new ChartPanel(barChart);
        panel.setPreferredSize(new java.awt.Dimension(560, 367));
        JFrame ventana = new JFrame("Grafica");
        ventana.setVisible(true);
        ventana.setSize(800, 600);
        ventana.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        ventana.add(panel);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Is a problem with this statistic.");
        }
    }//GEN-LAST:event_ButtonConfirm1ActionPerformed

    private void ButtonBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBack2ActionPerformed
        PanelPrincipalPage w = new PanelPrincipalPage();
        w.show();
        this.dispose();
    }//GEN-LAST:event_ButtonBack2ActionPerformed

    private void ButtonConfirm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfirm2ActionPerformed
        ConnectDB c = new ConnectDB();
        ResultSet q = c.query("sales_by_gender",true);
        DefaultPieDataset dataset = new DefaultPieDataset();
        try {
            while(q.next())
            {
                dataset.setValue(q.getString("gender") + q.getInt("sales"), q.getFloat("percentage"));
            }
            JFreeChart chart = ChartFactory.createPieChart("Sales by Gender", dataset, true, true, false);
        ChartPanel panel= new ChartPanel(chart);
        JFrame ventana = new JFrame("Grafica");
        ventana.setVisible(true);
        ventana.setSize(800, 600);
        ventana.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        ventana.add(panel);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Is a problem with this statistic.");
        }
    }//GEN-LAST:event_ButtonConfirm2ActionPerformed

    private void ButtonBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBack3ActionPerformed
        PanelPrincipalPage w = new PanelPrincipalPage();
        w.show();
        this.dispose();
    }//GEN-LAST:event_ButtonBack3ActionPerformed

    private void ButtonConfirm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfirm4ActionPerformed
        ConnectDB c = new ConnectDB();
        ResultSet q = c.query("products_by_category",true);
        DefaultPieDataset dataset = new DefaultPieDataset();
        try {
            while(q.next())
            {
                dataset.setValue(q.getString("category") + q.getInt("total_products"), q.getFloat("percentage"));
            }
            JFreeChart chart = ChartFactory.createPieChart("Products by Category", dataset, true, true, false);
        ChartPanel panel= new ChartPanel(chart);
        JFrame ventana = new JFrame("Grafica");
        ventana.setVisible(true);
        ventana.setSize(800, 600);
        ventana.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        ventana.add(panel);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Is a problem with this statistic.");
        }
    }//GEN-LAST:event_ButtonConfirm4ActionPerformed

    private void ButtonConfirm5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfirm5ActionPerformed
        ConnectDB c = new ConnectDB();
        ResultSet q = c.query("sales_by_gender",true);
        DefaultPieDataset dataset = new DefaultPieDataset();
        try {
            while(q.next())
            {
                dataset.setValue(q.getString("gender") + q.getInt("sales"), q.getFloat("percentage"));
            }
            JFreeChart chart = ChartFactory.createPieChart("Sales by Gender", dataset, true, true, false);
        ChartPanel panel= new ChartPanel(chart);
        JFrame ventana = new JFrame("Grafica");
        ventana.setVisible(true);
        ventana.setSize(800, 600);
        ventana.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        ventana.add(panel);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Is a problem with this statistic.");
        }
    }//GEN-LAST:event_ButtonConfirm5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statistics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxGender;
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton ButtonBack1;
    private javax.swing.JButton ButtonBack2;
    private javax.swing.JButton ButtonBack3;
    private javax.swing.JButton ButtonConfirm1;
    private javax.swing.JButton ButtonConfirm2;
    private javax.swing.JButton ButtonConfirm4;
    private javax.swing.JButton ButtonConfirm5;
    private javax.swing.JPanel PanelProductsCategory;
    private javax.swing.JPanel PanelTotalAmountSales;
    private javax.swing.JPanel PanelTotalSales;
    private javax.swing.JPanel PanelTotalSellers;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
