CREATE TABLE `order` (
  `id` int NOT NULL AUTO_INCREMENT,
  `price` decimal(3,0) DEFAULT NULL,
  `quantity` int DEFAULT NULL,
  `date` datetime DEFAULT NULL,
  `user_seller` varchar(20) DEFAULT NULL,
  `user_buyer` varchar(20) DEFAULT NULL,
  `id_product` int DEFAULT NULL,
  `creation_date` datetime DEFAULT NULL,
  `creation_user` varchar(45) DEFAULT NULL,
  `last_change_date` datetime DEFAULT NULL,
  `last_change_user` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_order_userSeller_idx` (`user_seller`),
  KEY `fk_order_userBuyer_idx` (`user_buyer`),
  KEY `fk_order_product_idx` (`id_product`),
  CONSTRAINT `fk_order_product` FOREIGN KEY (`id_product`) REFERENCES `product` (`id`),
  CONSTRAINT `fk_order_userBuyer` FOREIGN KEY (`user_buyer`) REFERENCES `user` (`username`),
  CONSTRAINT `fk_order_userSeller` FOREIGN KEY (`user_seller`) REFERENCES `user` (`username`)
) 